//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pizzachef.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public int CatNewsID { get; set; }
        public string Title { get; set; }
        public System.DateTime DatePost { get; set; }
        public string NewsContent { get; set; }
        public string Image { get; set; }
    
        public virtual CategoryNew CategoryNew { get; set; }
    }
}
